spring:
    profiles:
        active: dev
    datasource:
        password: password
        url: jdbc:h2:mem:testdb
        username: sa
        driverClassName: org.h2.Driver
    hateoas:
        use-hal-as-default-json-media-type: true
    data:
        jpa:
            repositories:
                bootstrap-mode: default
    jpa:
        database-platfom: org.hibernate.dialect.H2Dialect
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    h2:
        console:
            enabled: true
            path: /h2-console
server:
    port: 8081
    #servlet:
        #context-path: /web-ws/
        
app:
    jwtExpirationMs: 86400000
    jwtSecret: GHf9eFhtt312f10