spring:
    profiles:
        active: dev
    datasource:
        #password: sa
        url: jdbc:jdbc:h2:mem:testdb
        #username: root
    hateoas:
        use-hal-as-default-json-media-type: true
    data:
        jpa:
            repositories:
                bootstrap-mode: default
    h2:
        console:
            enabled: true
server:
    port: 8081
    servlet:
        context-path: /web-app-ws/api/v1
        
app:
    jwtExpirationMs: 86400000
    jwtSecret: GHf9eFhtt312f10